name: SRP
on:
  schedule:
    - cron: '*/05 * * * *'
  
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2 
          
      - name: Build with Maven
        run: |
          mvn test
